cc_test(
    name = "retry_test",
    srcs = [
        "retry_test.cpp",
    ],
    deps = [
        "//src/retry:retry",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

