cc_library(
    name = "retry",
    srcs = [
        "error_handler.cpp",
    ],
    hdrs = [
        "error_handler.hpp",
        "final_error_handler.hpp",
        "retry.hpp",
    ],
    include_prefix = "retry",
    visibility = ["//visibility:public"],
)

